GET http://localhost:3000/subscribers

###

PATCH  http://localhost:3000/subscribers/67c2f81642ac78ab29bdbf50
Content-Type: application/json

{
"name": "Amazing Kamila",
"subscribedToChannel": "Max Admit"
}
###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
"name": "Amazing person",
"subscribedToChannel": "Web Dev Sim"
}